test_eval[BERT_pytorch-cpu-eager]:
  norm: 0.05685180827858858
test_eval[BERT_pytorch-cpu-jit]:
  norm: 0.055031803058227524
test_eval[BERT_pytorch-cuda-eager]:
  norm: 0.021702383251048306
test_eval[BERT_pytorch-cuda-jit]:
  norm: 0.021699694322144733
test_eval[LearningToPaint-cpu-eager]:
  norm: 0.006393402419053018
test_eval[LearningToPaint-cpu-jit]:
  norm: 0.004743104493420379
test_eval[LearningToPaint-cuda-eager]:
  norm: 0.002253103726838475
test_eval[LearningToPaint-cuda-jit]:
  norm: 0.0021701873734609623
test_eval[Super_SloMo-cuda-eager]:
  norm: 0.43524276865064165
test_eval[Super_SloMo-cuda-jit]:
  norm: 0.4341700792079791
test_eval[alexnet-cpu-eager]:
  norm: 0.004451435620266021
test_eval[alexnet-cpu-jit]:
  norm: 0.00367016027414709
test_eval[alexnet-cuda-eager]:
  norm: 0.0019111540012111648
test_eval[alexnet-cuda-jit]:
  norm: 0.0018330485481532156
test_eval[attention_is_all_you_need_pytorch-cpu-eager]:
  norm: 0.23213776446064002
test_eval[attention_is_all_you_need_pytorch-cpu-jit]:
  norm: 0.22535653825616464
test_eval[attention_is_all_you_need_pytorch-cuda-eager]:
  norm: 0.14684644074877723
test_eval[attention_is_all_you_need_pytorch-cuda-jit]:
  norm: 0.14759871870628558
test_eval[demucs-cpu-eager]:
  norm: 0.08100289069698192
test_eval[demucs-cpu-jit]:
  norm: 0.07750276775914244
test_eval[demucs-cuda-eager]:
  norm: 0.07559058011393063
test_eval[demucs-cuda-jit]:
  norm: 0.07558373794890941
test_eval[densenet121-cpu-eager]:
  norm: 0.07553607149748132
test_eval[densenet121-cpu-jit]:
  norm: 0.03715926188009756
test_eval[densenet121-cuda-eager]:
  norm: 0.021485131590607318
test_eval[densenet121-cuda-jit]:
  norm: 0.010167109980770596
test_eval[dlrm-cpu-eager]:
  norm: 0.0004216417489431397
test_eval[dlrm-cuda-eager]:
  norm: 0.0007002152400178833
test_eval[drq-cpu-eager]:
  norm: 0.0022005594025981704
test_eval[drq-cuda-eager]:
  norm: 0.002008023756106609
test_eval[fastNLP-cpu-eager]:
  norm: 0.00016323325880957638
test_eval[fastNLP-cpu-jit]:
  norm: 0.00016097523587756205
test_eval[fastNLP-cuda-eager]:
  norm: 0.0001589085665232847
test_eval[fastNLP-cuda-jit]:
  norm: 0.00015518543208148462
test_eval[hf_Albert-cpu-eager]:
  norm: 0.09772425884730182
test_eval[hf_Albert-cuda-eager]:
  norm: 0.04419815310013845
test_eval[hf_Bart-cpu-eager]:
  norm: 0.11742897275835276
test_eval[hf_Bart-cuda-eager]:
  norm: 0.05496977909351699
test_eval[hf_Bert-cpu-eager]:
  norm: 0.09751313934684731
test_eval[hf_Bert-cuda-eager]:
  norm: 0.04375567055894467
test_eval[hf_BigBird-cpu-eager]:
  norm: 1.2016807637002784
test_eval[hf_BigBird-cuda-eager]:
  norm: 0.499124124716036
test_eval[hf_DistilBert-cpu-eager]:
  norm: 0.0541744910471607
test_eval[hf_DistilBert-cuda-eager]:
  norm: 0.024590896345993003
test_eval[hf_GPT2-cpu-eager]:
  norm: 0.2273902039974928
test_eval[hf_GPT2-cuda-eager]:
  norm: 0.10960107475984841
test_eval[hf_Longformer-cuda-eager]:
  norm: 0.47225784349720923
test_eval[hf_Reformer-cuda-eager]:
  norm: 0.043192895371854924
test_eval[hf_T5-cuda-eager]:
  norm: 0.27970010006101803
test_eval[maml-cpu-eager]:
  norm: 0.0731544112379197
test_eval[maml-cuda-eager]:
  norm: 0.038652029572986066
test_eval[maml_omniglot-cpu-eager]:
  norm: 0.0012007828018712726
test_eval[maml_omniglot-cuda-eager]:
  norm: 0.0006772385599433358
test_eval[mnasnet1_0-cpu-eager]:
  norm: 0.028053680166421045
test_eval[mnasnet1_0-cpu-jit]:
  norm: 0.004560569047720896
test_eval[mnasnet1_0-cuda-eager]:
  norm: 0.007641145853085618
test_eval[mnasnet1_0-cuda-jit]:
  norm: 0.09329594241571612
test_eval[mobilenet_v2-cpu-eager]:
  norm: 0.026743019241717104
test_eval[mobilenet_v2-cpu-jit]:
  norm: 0.004727411468047648
test_eval[mobilenet_v2-cuda-eager]:
  norm: 0.007848149609922002
test_eval[mobilenet_v2-cuda-jit]:
  norm: 0.0028030915268962937
test_eval[mobilenet_v3_large-cpu-eager]:
  norm: 0.02481118353685682
test_eval[mobilenet_v3_large-cpu-jit]:
  norm: 0.0072500658005462595
test_eval[mobilenet_v3_large-cuda-eager]:
  norm: 0.008977740710939873
test_eval[mobilenet_v3_large-cuda-jit]:
  norm: 0.008835531262252314
test_eval[moco-cuda-eager]:
  norm: 0.3917169963940978
test_eval[moco-cuda-jit]:
  norm: 0.39178658014861867
test_eval[nvidia_deeprecommender-cpu-eager]:
  norm: 0.0006867421893382585
test_eval[nvidia_deeprecommender-cuda-eager]:
  norm: 0.00049664774822611
test_eval[opacus_cifar10-cpu-eager]:
  norm: 0.010108650675071974
test_eval[opacus_cifar10-cuda-eager]:
  norm: 0.005105261504053114
test_eval[pyhpc_equation_of_state-cuda-eager]:
  norm: 0.17510420536855237
test_eval[pyhpc_equation_of_state-cuda-jit]:
  norm: 0.026043059898074716
test_eval[pyhpc_isoneutral_mixing-cpu-eager]:
  norm: 0.4638523310946766
test_eval[pyhpc_isoneutral_mixing-cpu-jit]:
  norm: 0.43386944198282434
test_eval[pyhpc_isoneutral_mixing-cuda-eager]:
  norm: 0.2388457236578688
test_eval[pyhpc_isoneutral_mixing-cuda-jit]:
  norm: 0.23644776335568168
test_eval[pytorch_CycleGAN_and_pix2pix-cuda-eager]:
  norm: 0.04049150848295539
test_eval[pytorch_CycleGAN_and_pix2pix-cuda-jit]:
  norm: 0.040490941437892614
test_eval[pytorch_stargan-cpu-eager]:
  norm: 0.4047150609374512
test_eval[pytorch_stargan-cpu-jit]:
  norm: 0.41127580269239844
test_eval[pytorch_stargan-cuda-eager]:
  norm: 0.08316384517820552
test_eval[pytorch_stargan-cuda-jit]:
  norm: 0.08326903133420274
test_eval[pytorch_struct-cpu-eager]:
  norm: 0.0018767721354542824
test_eval[pytorch_struct-cpu-jit]:
  norm: 0.0016678375671697974
test_eval[pytorch_struct-cuda-eager]:
  norm: 0.001154675792583211
test_eval[pytorch_struct-cuda-jit]:
  norm: 0.0009379383413847642
test_eval[resnet18-cpu-eager]:
  norm: 0.013635019411496516
test_eval[resnet18-cpu-jit]:
  norm: 0.004340000501205115
test_eval[resnet18-cuda-eager]:
  norm: 0.004029384374463939
test_eval[resnet18-cuda-jit]:
  norm: 0.002682424467818527
test_eval[resnet50-cpu-eager]:
  norm: 0.04178844787646085
test_eval[resnet50-cpu-jit]:
  norm: 0.010330284068351323
test_eval[resnet50-cuda-eager]:
  norm: 0.009906168770054263
test_eval[resnet50-cuda-jit]:
  norm: 0.006550707827699584
test_eval[resnet50_quantized_qat-cpu-eager]:
  norm: 0.010140954883712711
test_eval[resnext50_32x4d-cpu-eager]:
  norm: 0.04598601860925555
test_eval[resnext50_32x4d-cpu-jit]:
  norm: 0.010582654013935672
test_eval[resnext50_32x4d-cuda-eager]:
  norm: 0.01400644284456601
test_eval[resnext50_32x4d-cuda-jit]:
  norm: 0.01067127727315222
test_eval[shufflenet_v2_x1_0-cpu-eager]:
  norm: 0.02395763971366077
test_eval[shufflenet_v2_x1_0-cpu-jit]:
  norm: 0.006669298970761398
test_eval[shufflenet_v2_x1_0-cuda-eager]:
  norm: 0.009757025870403238
test_eval[shufflenet_v2_x1_0-cuda-jit]:
  norm: 0.002579170347267772
test_eval[soft_actor_critic-cuda-eager]:
  norm: 0.009121270070318132
test_eval[speech_transformer-cuda-eager]:
  norm: 5.5849457436881496
test_eval[squeezenet1_1-cpu-eager]:
  norm: 0.006074640442091583
test_eval[squeezenet1_1-cpu-jit]:
  norm: 0.0038062207445777444
test_eval[squeezenet1_1-cuda-eager]:
  norm: 0.002710926708199882
test_eval[squeezenet1_1-cuda-jit]:
  norm: 0.001186003432805511
test_eval[timm_efficientnet-cpu-eager]:
  norm: 0.044931364559527974
test_eval[timm_efficientnet-cpu-jit]:
  norm: 0.03572538075165759
test_eval[timm_efficientnet-cuda-eager]:
  norm: 0.01540701630919312
test_eval[timm_efficientnet-cuda-jit]:
  norm: 0.011456383694894611
test_eval[timm_nfnet-cpu-eager]:
  norm: 0.0975031184963882
test_eval[timm_nfnet-cpu-jit]:
  norm: 0.038357658824814414
test_eval[timm_nfnet-cuda-eager]:
  norm: 0.027364568989346357
test_eval[timm_nfnet-cuda-jit]:
  norm: 0.014976983203087001
test_eval[timm_regnet-cpu-eager]:
  norm: 0.017570307016732137
test_eval[timm_regnet-cpu-jit]:
  norm: 0.011412880346882915
test_eval[timm_regnet-cuda-eager]:
  norm: 0.014374228069625263
test_eval[timm_regnet-cuda-jit]:
  norm: 0.008740643330384046
test_eval[timm_resnest-cpu-eager]:
  norm: 0.018055407446809113
test_eval[timm_resnest-cpu-jit]:
  norm: 0.009004193994801788
test_eval[timm_resnest-cuda-eager]:
  norm: 0.004720946368364114
test_eval[timm_resnest-cuda-jit]:
  norm: 0.003411335503038223
test_eval[timm_vision_transformer-cpu-eager]:
  norm: 0.028372901728075436
test_eval[timm_vision_transformer-cpu-jit]:
  norm: 0.026077427709399647
test_eval[timm_vision_transformer-cuda-eager]:
  norm: 0.010017510026227684
test_eval[timm_vision_transformer-cuda-jit]:
  norm: 0.010030586841749027
test_eval[timm_vovnet-cpu-eager]:
  norm: 0.027096056266108882
test_eval[timm_vovnet-cpu-jit]:
  norm: 0.01888504956260253
test_eval[timm_vovnet-cuda-eager]:
  norm: 0.008244240238939313
test_eval[timm_vovnet-cuda-jit]:
  norm: 0.007820618220648612
test_eval[tts_angular-cpu-eager]:
  norm: 0.21736741150380112
test_eval[tts_angular-cuda-eager]:
  norm: 0.21865387795260177
test_eval[vgg16-cpu-eager]:
  norm: 0.0235548484989247
test_eval[vgg16-cpu-jit]:
  norm: 0.01803949294428873
test_eval[vgg16-cuda-eager]:
  norm: 0.010237725238952482
test_eval[vgg16-cuda-jit]:
  norm: 0.009331264427466388
test_eval[yolov3-cpu-eager]:
  norm: 0.5728399513871409
test_eval[yolov3-cuda-eager]:
  norm: 0.5914560730627272
test_train[BERT_pytorch-cpu-eager]:
  norm: 0.2708426495781168
test_train[BERT_pytorch-cuda-eager]:
  norm: 0.09856361297424883
test_train[BERT_pytorch-cuda-jit]:
  norm: 0.0985544886381831
test_train[Background_Matting-cuda-eager]:
  norm: 3.0283131372358185
test_train[Background_Matting-cuda-jit]:
  norm: 2.999387426796602
test_train[LearningToPaint-cuda-eager]:
  norm: 0.015633818888678572
test_train[LearningToPaint-cuda-jit]:
  norm: 0.015593177889968501
test_train[Super_SloMo-cuda-eager]:
  norm: 1.294785407895688
test_train[Super_SloMo-cuda-jit]:
  norm: 1.2860810891608707
test_train[alexnet-cpu-eager]:
  norm: 0.47772624749923126
test_train[alexnet-cpu-jit]:
  norm: 0.44585217649582776
test_train[alexnet-cuda-eager]:
  norm: 0.1466525606054347
test_train[alexnet-cuda-jit]:
  norm: 0.1469080216542352
test_train[attention_is_all_you_need_pytorch-cpu-eager]:
  norm: 0.9252178588940296
test_train[attention_is_all_you_need_pytorch-cuda-eager]:
  norm: 0.4498943536076695
test_train[attention_is_all_you_need_pytorch-cuda-jit]:
  norm: 0.4637195066025015
test_train[demucs-cpu-eager]:
  norm: 0.35094974825624375
test_train[demucs-cpu-jit]:
  norm: 0.3420691429171711
test_train[demucs-cuda-eager]:
  norm: 0.16359462569234892
test_train[demucs-cuda-jit]:
  norm: 0.1790315533406101
test_train[densenet121-cpu-eager]:
  norm: 4.252127235056832
test_train[densenet121-cpu-jit]:
  norm: 4.030624402605463
test_train[densenet121-cuda-eager]:
  norm: 1.099380482948618
test_train[densenet121-cuda-jit]:
  norm: 1.101066642801743
test_train[dlrm-cpu-eager]:
  norm: 0.001675497455914636
test_train[dlrm-cuda-eager]:
  norm: 0.0029999223756419897
test_train[drq-cuda-eager]:
  norm: 0.37399630259606054
test_train[fastNLP-cpu-eager]:
  norm: 0.002490660204647012
test_train[fastNLP-cpu-jit]:
  norm: 0.0024541725559404245
test_train[fastNLP-cuda-eager]:
  norm: 0.0016545301823255917
test_train[fastNLP-cuda-jit]:
  norm: 0.0017692114719573188
test_train[hf_Albert-cpu-eager]:
  norm: 9.163557240861701
test_train[hf_Albert-cuda-eager]:
  norm: 2.6388653837144376
test_train[hf_Bart-cpu-eager]:
  norm: 22.438752913649658
test_train[hf_Bart-cuda-eager]:
  norm: 2.0085758237924893
test_train[hf_Bert-cpu-eager]:
  norm: 13.291868388210423
test_train[hf_Bert-cuda-eager]:
  norm: 1.5477299488033167
test_train[hf_BigBird-cpu-eager]:
  norm: 13.864226462866645
test_train[hf_BigBird-cuda-eager]:
  norm: 2.9844093741616233
test_train[hf_DistilBert-cpu-eager]:
  norm: 15.872414556553121
test_train[hf_DistilBert-cuda-eager]:
  norm: 1.6961384260444903
test_train[hf_GPT2-cuda-eager]:
  norm: 1.8896846601506696
test_train[hf_Longformer-cuda-eager]:
  norm: 2.9638905459840315
test_train[hf_Reformer-cuda-eager]:
  norm: 3.6887837688904255
test_train[hf_T5-cpu-eager]:
  norm: 23.340448434354037
test_train[hf_T5-cuda-eager]:
  norm: 1.463875985494815
test_train[maml-cpu-eager]:
  norm: 1.3019665106898173
test_train[maml-cuda-eager]:
  norm: 0.6724238628405146
test_train[maml_omniglot-cpu-eager]:
  norm: 8.851909254927886
test_train[maml_omniglot-cuda-eager]:
  norm: 5.604426171915838
test_train[mnasnet1_0-cpu-eager]:
  norm: 1.3341582181106788
test_train[mnasnet1_0-cpu-jit]:
  norm: 1.324990783096291
test_train[mnasnet1_0-cuda-eager]:
  norm: 0.4080575111496728
test_train[mnasnet1_0-cuda-jit]:
  norm: 0.4086199810903054
test_train[mobilenet_v2-cuda-eager]:
  norm: 0.4129796772554982
test_train[mobilenet_v2-cuda-jit]:
  norm: 0.4134394217457157
test_train[mobilenet_v2_quantized_qat-cuda-eager]:
  norm: 2.126267044339329
test_train[mobilenet_v3_large-cuda-eager]:
  norm: 0.3583611252019182
test_train[mobilenet_v3_large-cuda-jit]:
  norm: 0.359058400336653
test_train[moco-cuda-eager]:
  norm: 0.8935477602062747
test_train[moco-cuda-jit]:
  norm: 0.893567960546352
test_train[nvidia_deeprecommender-cpu-eager]:
  norm: 0.020129228197038173
test_train[nvidia_deeprecommender-cuda-eager]:
  norm: 0.007889746911013905
test_train[opacus_cifar10-cuda-eager]:
  norm: 0.09436536704888568
test_train[pytorch_CycleGAN_and_pix2pix-cuda-eager]:
  norm: 79.31401049535489
test_train[pytorch_stargan-cpu-eager]:
  norm: 4.684396562050097
test_train[pytorch_stargan-cpu-jit]:
  norm: 4.6352093189430885
test_train[pytorch_struct-cuda-eager]:
  norm: 0.21134436799911782
test_train[pytorch_struct-cuda-jit]:
  norm: 0.21108390938607044
test_train[resnet18-cuda-eager]:
  norm: 0.31470131579553706
test_train[resnet18-cuda-jit]:
  norm: 0.31473775453632696
test_train[resnet50-cuda-eager]:
  norm: 1.009949930314906
test_train[resnet50-cuda-jit]:
  norm: 1.0101281055482105
test_train[resnet50_quantized_qat-cuda-eager]:
  norm: 1.790898621699307
test_train[resnext50_32x4d-cuda-eager]:
  norm: 1.4122814904490952
test_train[resnext50_32x4d-cuda-jit]:
  norm: 1.4122600037255324
test_train[shufflenet_v2_x1_0-cpu-eager]:
  norm: 0.5974261967523489
test_train[shufflenet_v2_x1_0-cpu-jit]:
  norm: 0.5763862078019883
test_train[shufflenet_v2_x1_0-cuda-eager]:
  norm: 0.1883382234547753
test_train[shufflenet_v2_x1_0-cuda-jit]:
  norm: 0.18924647256499155
test_train[soft_actor_critic-cpu-eager]:
  norm: 0.02960307927980252
test_train[soft_actor_critic-cuda-eager]:
  norm: 0.014834040953124414
test_train[speech_transformer-cuda-eager]:
  norm: 11.121826122497442
test_train[squeezenet1_1-cpu-eager]:
  norm: 0.42564678501221354
test_train[squeezenet1_1-cpu-jit]:
  norm: 0.42193049514316955
test_train[squeezenet1_1-cuda-eager]:
  norm: 0.18022485449328088
test_train[squeezenet1_1-cuda-jit]:
  norm: 0.18207195854047314
test_train[timm_efficientnet-cuda-eager]:
  norm: 0.5234629307407885
test_train[timm_efficientnet-cuda-jit]:
  norm: 0.5235117086966057
test_train[timm_nfnet-cuda-eager]:
  norm: 1.0027130784699694
test_train[timm_nfnet-cuda-jit]:
  norm: 1.003045166103402
test_train[timm_regnet-cuda-eager]:
  norm: 0.14915518699563107
test_train[timm_regnet-cuda-jit]:
  norm: 0.14913190535153262
test_train[timm_resnest-cuda-eager]:
  norm: 0.4128380549547728
test_train[timm_resnest-cuda-jit]:
  norm: 0.41285178575781173
test_train[timm_vision_transformer-cuda-eager]:
  norm: 1.1331409125763456
test_train[timm_vision_transformer-cuda-jit]:
  norm: 1.1313964793051128
test_train[timm_vovnet-cuda-eager]:
  norm: 0.6450615282461513
test_train[timm_vovnet-cuda-jit]:
  norm: 0.6447867099021096
test_train[tts_angular-cpu-eager]:
  norm: 0.45835460198577493
test_train[tts_angular-cuda-eager]:
  norm: 0.4574360223952681
test_train[vgg16-cuda-eager]:
  norm: 1.492201897542691
test_train[vgg16-cuda-jit]:
  norm: 1.4922273806063457
test_train[yolov3-cuda-eager]:
  norm: 13.348495351942256
