[build-system]
requires = ["setuptools", "wheel"]
# Use legacy backend to import local packages in setup.py
build-backend = "setuptools.build_meta:__legacy__"


[tool.black]
line-length = 88
target-version = ["py38"]
exclude = '''/submodules/.*'''

[tool.usort]
excludes = ["**/submodules/**"]
