# Sample benchmark config
# Runs a test matrix of [device x test x test_args]
# Currently, `summarize.py` only supports single device and single test
# The first combination will be used as the baseline
# In this example, baseline is ("cuda", "eval", "")
device:
  - "cuda"
test:
  - "eval"
args:
  # empty argument means the default pytorch eager mode
  - ""
  - "--torchdynamo cudagraph"
