version: 2

jobs:
  run_benchmarks:
    machine:
      image: ubuntu-1604:201903-01
    resource_class: gpu.nvidia.medium
    steps:
      - checkout
      - run:
          name: Setup CI environment
          command: ./scripts/setup_ci.sh
      - run:
          name: Install Conda
          command: ./scripts/install_basics.sh
      - run:
          name: Install CUDA 11.2
          command: sudo ./scripts/install_cuda.sh
      - run:
          name: Install PyTorch nightly
          command: ./scripts/install_nightlies.sh
      - run:
          name: Setup benchmark suite dependencies
          command: . ~/miniconda3/etc/profile.d/conda.sh; conda activate base; python install.py
      - run:
          name: Validate compute_score.py
          command: |
            wget -O example.json https://s3.amazonaws.com/ossci-metrics/torchbench_v0_nightly/gh741259573/20210412_131220_1.json
            . ~/miniconda3/etc/profile.d/conda.sh; conda activate base; python compute_score.py --configuration v0 --benchmark_data_file example.json
      - run:
          name: Validate training benchmark suite
          command: . ~/miniconda3/etc/profile.d/conda.sh; conda activate base; python test.py
          no_output_timeout: "30m"
      - run:
          name: Validate pytest-benchmark invocation of training suite
          command: ./scripts/run_bench_and_upload.sh
          no_output_timeout: "30m"

workflows:
  version: 2
  workflow-build:
    jobs:
      - run_benchmarks
  nightly:
    triggers:
      - schedule:
          cron: "0 0,12 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - run_benchmarks
