version: 2

jobs:
  run_benchmarks:
    machine:
      image: ubuntu-1604:201903-01
    resource_class: gpu.small
    steps:
      - checkout
      - run:
          name: Setup CI environment
          command: ./scripts/setup_ci.sh
      - run:
          name: Install Conda
          command: ./scripts/install_basics.sh
      - run:
          name: Install PyTorch nightly
          command: ./scripts/install_nightlies.sh
      - run:
          name: Setup benchmark suite dependencies
          command: . ~/miniconda3/etc/profile.d/conda.sh; conda activate base; python install.py
      - run:
          name: Validate training benchmark suite
          command: . ~/miniconda3/etc/profile.d/conda.sh; conda activate base; python test.py
      - run:
          name: Validate pytest-benchmark invocation of training suite
          command: ./scripts/run_bench_and_upload.sh

workflows:
  version: 2
  workflow-build:
    jobs:
      - run_benchmarks
  nightly:
    triggers:
      - schedule:
          cron: "0 0,12 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - run_benchmarks
