model: "*"
extended_models:
  - huggingface
  - timm
test: eval
device: cuda
extra_args: --precision bf16 --torchdynamo inductor --inductor-compile-mode max-autotune
metrics:
  - latencies
  - gpu_peak_mem
test_group:
  test_batch_size_default:
    subgroup:
      - extra_args: --quantization noquant
      - extra_args: --quantization autoquant
