# Sample benchmark config
# Runs a test matrix of [device x test x models x precisions x test_args]
# Currently, `summarize.py` only supports sinxxgle device and single test
# The first combination will be used as the baseline
# In this example, baseline is ("cuda", "eval", "fp32")
device:
  - "cuda"
test:
  - "eval"
models:
  - "alexnet"
  - "attention_is_all_you_need_pytorch"
  - "BERT_pytorch"
  - "hf_Bert"
  - "nvidia_deeprecommender"
  - "resnet18"
precision:
  - "fp16"
  - "fp32"
args:
  # empty argument means the default pytorch eager mode
  - ""
  # script based
  - "--backend blade"
  - "--backend blade --trt"
  - "--jit"
  - "--fuser fuser2 --jit"  # nvfuser

  # torchdynamo based
  - "--torchdynamo eager"
  - "--torchdynamo nvfuser"
  - "--torchdynamo blade_optimize_dynamo"
  - "--torchdynamo blade_optimize_dynamo --trt"
  - "--torchdynamo cudagraphs"
